# Generated by Django 2.2.20 on 2021-06-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=500)),
                ('description2', models.CharField(max_length=1000)),
                ('feature1', models.CharField(blank=True, default=' ', max_length=300, null=True)),
                ('feature2', models.CharField(blank=True, default=' ', max_length=300, null=True)),
                ('feature3', models.CharField(blank=True, default=' ', max_length=300, null=True)),
                ('feature4', models.CharField(blank=True, default=' ', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=500, null=True)),
                ('description2', models.CharField(max_length=1000, null=True)),
                ('feature1', models.CharField(blank=True, default=' ', max_length=300, null=True)),
                ('feature2', models.CharField(blank=True, default=' ', max_length=300, null=True)),
                ('feature3', models.CharField(blank=True, default=' ', max_length=300, null=True)),
                ('feature4', models.CharField(blank=True, default=' ', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='static/img/team/')),
                ('post', models.CharField(blank=True, default='#', max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, default='#', max_length=1000, null=True)),
                ('twitter', models.CharField(blank=True, default='#', max_length=1000, null=True)),
                ('instagram', models.CharField(blank=True, default='#', max_length=1000, null=True)),
                ('linkedin', models.CharField(blank=True, default='#', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/img/testimonial/')),
                ('post', models.CharField(max_length=100)),
                ('quote', models.TextField()),
            ],
        ),
    ]
