# Generated by Django 2.2.20 on 2021-06-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description1', models.CharField(max_length=500)),
                ('description2', models.TextField()),
                ('topic1', models.CharField(max_length=150)),
                ('answer1', models.TextField()),
                ('topic2', models.CharField(max_length=150)),
                ('answer2', models.TextField()),
                ('topic3', models.CharField(max_length=150)),
                ('answer3', models.TextField()),
            ],
        ),
    ]
