# Generated by Django 2.2.20 on 2021-08-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contactus_digitalmarketing_domainhosting_graphicdesign_mobiledevelopment_softwaredevelopment_videoed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
    ]
